# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'authorization.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import app.services.authorization as auth
import mainwindow
import gui_utils


def is_correct_input_data(email: str, name: str, password: str):
    check1 = not email.isspace() and not name.isspace() and not password.isspace()
    check2 = email != "" and name != "" and password != ""
    # check3 = auth.seller_ind(email, name, password) != -1
    return check1 and check2



class Ui_AuthorizationWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 750)
        MainWindow.setMinimumSize(QtCore.QSize(450, 750))
        MainWindow.setMaximumSize(QtCore.QSize(450, 750))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_label_authorization = QtWidgets.QLabel(self.centralwidget)
        self.text_label_authorization.setGeometry(QtCore.QRect(50, 10, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text_label_authorization.setFont(font)
        self.text_label_authorization.setStyleSheet("color: rgb(38, 162, 105);")
        self.text_label_authorization.setAlignment(QtCore.Qt.AlignCenter)
        self.text_label_authorization.setObjectName("text_label_authorization")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 90, 311, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_email = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.horizontalLayout.addWidget(self.lineEdit_email)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(40, 180, 311, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.lineEdit_name = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout_3.addWidget(self.lineEdit_name)
        self.pushButton_authoriz = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_authoriz.setGeometry(QtCore.QRect(40, 620, 371, 41))
        self.pushButton_authoriz.setStyleSheet("background-color: rgb(87, 227, 137);")
        self.pushButton_authoriz.setObjectName("pushButton_authoriz")
        self.pushButton_authoriz.clicked.connect(self.handle_authorize)

        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(40, 290, 311, 61))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lineEdit_password = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.horizontalLayout_4.addWidget(self.lineEdit_password)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scamberries - Авторизация"))
        self.text_label_authorization.setText(_translate("MainWindow", "Авторизация"))
        self.label_3.setText(_translate("MainWindow", "email:"))
        self.label_5.setText(_translate("MainWindow", "Ник / Назавние магазина:"))
        self.pushButton_authoriz.setText(_translate("MainWindow", "Войти в аккаунт"))
        self.label_7.setText(_translate("MainWindow", "password:"))

    def handle_authorize(self):
        import app.services.registration as reg
        email: str = self.lineEdit_email.text()
        name: str = self.lineEdit_name.text()
        password: str = self.lineEdit_password.text()
        if not is_correct_input_data(email, name, password):
            # print("неверные данные")
            return
        seller_index = auth.seller_ind(email, name, password)
        if seller_index != -1:
            from seller_mode_window import Ui_SellerModeWindow
            mainwindow.current_seller_account_ind = seller_index
            tel_num = reg.registered_sellers[seller_index].phone_num
            gui_utils.change_window(Ui_SellerModeWindow(), name, email, tel_num)

        buyer_index = auth.buyer_ind(email, name, password)
        if buyer_index != -1:
            from buyer_mode_window import Ui_BuyerModeWindow
            mainwindow.current_buyer_account_ind = buyer_index
            tel_num = reg.registered_buyers[buyer_index].phone_num
            gui_utils.change_window(Ui_BuyerModeWindow())
