# -*- coding: utf-8 -*-
from cgitb import handler

# Form implementation generated from reading ui file 'registration_process_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import app.services.registration as reg
from PyQt5.QtWidgets import QMessageBox


def is_correct_input_data(is_seller: bool, is_buyer: bool, email: str, tel_num: str, name: str):
    check1 = not email.isspace() and not tel_num.isspace() and not name.isspace()
    check2 = (is_seller and not is_buyer) or (not is_seller and is_buyer)
    check3 = email != "" and tel_num != "" and name != ""
    return check1 and check2 and check3




class Ui_RegistrationWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 750)
        MainWindow.setMinimumSize(QtCore.QSize(450, 750))
        MainWindow.setMaximumSize(QtCore.QSize(450, 750))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_label_registration = QtWidgets.QLabel(self.centralwidget)
        self.text_label_registration.setGeometry(QtCore.QRect(50, 10, 351, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.text_label_registration.setFont(font)
        self.text_label_registration.setStyleSheet("color: rgb(38, 162, 105);")
        self.text_label_registration.setAlignment(QtCore.Qt.AlignCenter)
        self.text_label_registration.setObjectName("text_label_registration")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 90, 160, 131))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.radioButton_is_buyer = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_is_buyer.setObjectName("radioButton_is_buyer")
        self.verticalLayout.addWidget(self.radioButton_is_buyer)
        self.radioButton_is_seller = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButton_is_seller.setObjectName("radioButton_is_seller")
        self.verticalLayout.addWidget(self.radioButton_is_seller)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(40, 250, 311, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_email = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.horizontalLayout.addWidget(self.lineEdit_email)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(40, 330, 311, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEdit_tel_number = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_tel_number.setObjectName("lineEdit_tel_number")
        self.horizontalLayout_2.addWidget(self.lineEdit_tel_number)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(40, 410, 311, 80))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.lineEdit_name = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout_3.addWidget(self.lineEdit_name)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(40, 530, 301, 16))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 620, 371, 41))
        self.pushButton.setStyleSheet("background-color: rgb(87, 227, 137);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.handle_register)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 450, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RegistrationWindow"))
        self.text_label_registration.setText(_translate("MainWindow", "Регистрация"))
        self.label_2.setText(_translate("MainWindow", "Ваша роль:"))
        self.radioButton_is_buyer.setText(_translate("MainWindow", "Покупатель"))
        self.radioButton_is_seller.setText(_translate("MainWindow", "Продавец"))
        self.label_3.setText(_translate("MainWindow", "email:"))
        self.label_4.setText(_translate("MainWindow", "Номер тел."))
        self.label_5.setText(_translate("MainWindow", "Ник / Назавние магазина:"))
        self.checkBox.setText(_translate("MainWindow", "Поставьте галачку (ВАЖНО)"))
        self.pushButton.setText(_translate("MainWindow", "Зарегистрироваться"))

    def handle_register(self):
        is_seller: bool = self.radioButton_is_seller.isChecked()
        is_buyer: bool = self.radioButton_is_buyer.isChecked()
        email: str = self.lineEdit_email.text()
        tel_number: str = self.lineEdit_tel_number.text()
        name: str = self.lineEdit_name.text()
        if not is_correct_input_data(is_seller, is_buyer, email, tel_number, name):
            # <здесь> открыть сплывающее окно
            print("неверные данные")
            return

        if is_seller:
            print("Добавлен аккаунт продавца")
            reg.register_seller(email, tel_number, name)
        elif is_buyer:
            print("Добавлен аккаунт покупателя")
            reg.register_buyer(email, tel_number, name)

