# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'seller_mode_window1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import mainwindow
import gui_utils


class Ui_SellerModeWindow(object):
    def setupUi(self, MainWindow, name: str, email: str, tel_num: str):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 750)
        MainWindow.setMinimumSize(QtCore.QSize(450, 750))
        MainWindow.setMaximumSize(QtCore.QSize(450, 750))
        MainWindow.setStyleSheet("background-color: rgb(255, 190, 111);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-40, 0, 491, 61))
        self.label.setStyleSheet("background-color: rgb(119, 118, 123);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_Exit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Exit.setGeometry(QtCore.QRect(360, 17, 71, 31))
        self.pushButton_Exit.setStyleSheet("background-color: rgb(224, 27, 36);")
        self.pushButton_Exit.setObjectName("pushButton")
        self.pushButton_Exit.clicked.connect(self.handle_exit)

        self.pushButton_Home = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Home.setGeometry(QtCore.QRect(270, 17, 71, 31))
        self.pushButton_Home.setStyleSheet("background-color: rgb(51, 209, 122);")
        self.pushButton_Home.setObjectName("pushButton_Home")
        self.pushButton_Home.clicked.connect(self.handle_home)

        self.label__name = QtWidgets.QLabel(self.centralwidget)
        self.label__name.setGeometry(QtCore.QRect(20, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label__name.setFont(font)
        self.label__name.setObjectName("label_2")
        self.label__email = QtWidgets.QLabel(self.centralwidget)
        self.label__email.setGeometry(QtCore.QRect(20, 130, 61, 22))
        self.label__email.setObjectName("label_3")
        self.label_telnum = QtWidgets.QLabel(self.centralwidget)
        self.label_telnum.setGeometry(QtCore.QRect(20, 160, 81, 22))
        self.label_telnum.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-10, 60, 481, 141))
        self.label_5.setStyleSheet("background-color: rgb(255, 190, 111);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(-10, 200, 471, 561))
        self.label_6.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_lookAllCards = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_lookAllCards.setGeometry(QtCore.QRect(50, 230, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_lookAllCards.setFont(font)
        self.pushButton_lookAllCards.setStyleSheet("background-color: rgb(246, 245, 244);")
        self.pushButton_lookAllCards.setObjectName("pushButton_lookAllCards")
        self.pushButton_lookAllCards.clicked.connect(self.handle_watch_cards)

        self.pushButton_addCard = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_addCard.setGeometry(QtCore.QRect(50, 290, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_addCard.setFont(font)
        self.pushButton_addCard.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"color: rgb(51, 209, 122);")
        self.pushButton_addCard.setObjectName("pushButton_addCard")
        self.pushButton_addCard.clicked.connect(self.handle_add_card_button)

        self.label_NAME = QtWidgets.QLabel(self.centralwidget)
        self.label_NAME.setGeometry(QtCore.QRect(120, 80, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_NAME.setFont(font)
        self.label_NAME.setObjectName("label_NAME")
        self.label_NAME.setText(name)

        self.label_EMAIL = QtWidgets.QLabel(self.centralwidget)
        self.label_EMAIL.setGeometry(QtCore.QRect(80, 130, 371, 22))
        self.label_EMAIL.setObjectName("label_EMAIL")
        self.label_EMAIL.setText(email)

        self.label_TELNUM = QtWidgets.QLabel(self.centralwidget)
        self.label_TELNUM.setGeometry(QtCore.QRect(100, 160, 371, 22))
        self.label_TELNUM.setObjectName("label_9")
        self.label_TELNUM.setText(tel_num)

        self.label_5.raise_()
        self.label.raise_()
        self.pushButton_Exit.raise_()
        self.pushButton_Home.raise_()
        self.label__name.raise_()
        self.label__email.raise_()
        self.label_telnum.raise_()
        self.label_6.raise_()
        self.pushButton_lookAllCards.raise_()
        self.pushButton_addCard.raise_()
        self.label_NAME.raise_()
        self.label_EMAIL.raise_()
        self.label_TELNUM.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scamberries"))
        self.pushButton_Exit.setText(_translate("MainWindow", "Exit"))
        self.pushButton_Home.setText(_translate("MainWindow", "Home"))
        self.label__name.setText(_translate("MainWindow", "Name:"))
        self.label__email.setText(_translate("MainWindow", "email:"))
        self.label_telnum.setText(_translate("MainWindow", "tel. num:"))
        self.pushButton_lookAllCards.setText(_translate("MainWindow", "Просмотреть все карточки"))
        self.pushButton_addCard.setText(_translate("MainWindow", "Добавить карточку"))

    def handle_home(self):
        gui_utils.change_window(Ui_SellerModeWindow(), self.label_NAME.text(), self.label_EMAIL.text(),
                                self.label_TELNUM.text())

    def handle_exit(self):
        from welcome_window import Ui_WelcomeWindow
        gui_utils.change_window(Ui_WelcomeWindow())

    def handle_add_card_button(self):
        from creating_card_window import Ui_AddCardWindow
        gui_utils.change_window(Ui_AddCardWindow())

    def handle_watch_cards(self):
        from watch_card_info_window import Ui_WatchCardsWindowSeller
        import app.services.registration as reg
        if not reg.registered_sellers[mainwindow.current_seller_account_ind].is_empty_list_cards():
            gui_utils.change_window(Ui_WatchCardsWindowSeller())
